@HostAddress = http://localhost:5102

### healthcheck
GET {{HostAddress}}/api/health
Accept: application/json

###

### get all projects
GET {{HostAddress}}/api/projects
Accept: application/json

###

### get project by id
GET {{HostAddress}}/api/projects/{8D32E6AC-59E4-4253-82D3-82E30B88A171}
Accept: application/json
###

### get project with a different id
GET {{HostAddress}}/api/projects/{00224DE4-59B5-4085-976D-97B07890FEF9}
Accept: application/json

###

### get model attributes for project 1
GET {{HostAddress}}/api/projects/{8D32E6AC-59E4-4253-82D3-82E30B88A171}/model-attributes
Accept: application/json

### get model attributes for project 2
GET {{HostAddress}}/api/projects/{00224DE4-59B5-4085-976D-97B07890FEF9}/model-attributes
Accept: application/json
###

### get cost breakdown by scope for project
GET {{HostAddress}}/api/projects/{8D32E6AC-59E4-4253-82D3-82E30B88A171}/cost-breakdown/scope
Accept: application/json